---
- name: custom remediation
  hosts: rhel9
  become: true
  tasks:
  - name: ensure /etc/gdm directory exists
    file:
      path: /etc/gdm
      state: directory
      mode: '0755'
  - name: create a dummy GDM configuration file since GDM is not installed
    copy:
      dest: /etc/gdm/custom.conf
      content: |
        [daemon]
        AutomaticLoginEnable=false
      mode: '0644'
  - name: disable the "nullok" option via authselect
    command: "{{ item }}"
    loop:
      - authselect select sssd --force 
      - authselect enable-feature without-nullok
      - authselect apply-changes
  - name: ensure kernel.yama.ptrace_scope is set in sysctl configuration
    copy:
      dest: /etc/sysctl.d/99-stig-hardening.conf
      content: |
        kernel.yama.ptrace_scope = 1
      mode: '0644'
  - name: reload sysctl settings to apply changes
    command: sysctl --system
  - name: ensure /home has nodev, nosuid, and noexec options in /etc/fstab
    lineinfile:
      path: /etc/fstab
      regexp: '^(.*\s+/home\s+\S+\s+)(\S*)\s+(\d+\s+\d+)$'
      line: '\1\2,nodev,nosuid,noexec \3'
      backrefs: yes
  - name: remount /home with new options
    command: mount -o remount /home
  - name: ensure /boot has the nosuid option in /etc/fstab
    lineinfile:
      path: /etc/fstab
      regexp: '^(.*\s+/boot\s+\S+\s+)(\S*)\s+(\d+\s+\d+)$'
      line: '\1\2,nosuid \3'
      backrefs: yes
  - name: remount /boot with the nosuid option
    command: mount -o remount /boot
  - name: enable pcscd
    service:
      name: pcscd
      state: restarted
      enabled: true
  - name: remove umask 022 condition in /etc/bashrc
    replace:
      path: /etc/bashrc
      regexp: '^\s*\[ `umask` -eq 0 \] && umask 022'
      replace: ''
  - name: remove umask 022 conditional block from /etc/csh.cshrc
    replace:
      path: /etc/csh.cshrc
      regexp: '^\s*if \( `umask` == 0 \) then\s*\n\s*umask 022\s*\n\s*endif\s*\n'
      replace: ''
  - name: ensure /etc/profile.d/tmout.sh exists and sets TMOUT=600
    copy:
      dest: /etc/profile.d/tmout.sh
      content: |
        #!/bin/bash
        declare -xr TMOUT=600
      mode: '0644'
  - name: ensure /etc/profile.d/tmout.sh is executable
    file:
      path: /etc/profile.d/tmout.sh
      mode: '0755'
  - name: ensure X11Forwarding is set to no
    lineinfile:
      path: "{{ item }}"
      regexp: '^X11Forwarding\s+'
      line: 'X11Forwarding no'
    loop:
      - /etc/ssh/sshd_config.d/50-redhat.conf
      - /etc/ssh/sshd_config
  - name: restart SSH service to apply changes
    systemd:
      name: sshd
      state: restarted
  - name: set password max age to 60 days
    shell: "passwd -x 60 {{ item }}"
    loop:
      - ansible
      - root
  - name: enforce a 24 hour minimum password lifetime
    shell: "passwd -n 1 {{ item }}"
    loop:
      - ansible
  - name: ensure StopIdleSessionSec=900 is set in /etc/systemd/logind.conf
    lineinfile:
      path: /etc/systemd/logind.conf
      regexp: '^#?StopIdleSessionSec='
      line: 'StopIdleSessionSec=900'
  - name: restart systemd-logind service to apply changes
    systemd:
      name: systemd-logind
      state: restarted
  - name: ensure "pam_wheel.so use_uid" is uncommented in /etc/pam.d/su
    replace:
      path: /etc/pam.d/su
      regexp: '^\s*#\s*(auth\s+required\s+pam_wheel\.so\s+use_uid)'
      replace: '\1'
  - name: ensure "PermitRootLogin no" is set in sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
      state: present
  - name: restart SSH service to apply changes
    systemd:
      name: sshd
      state: restarted
