---

- name: initial-setup
  hosts: all
  tasks:
  - name: create password hash
    set_fact: 
      pw_hash: "{{ 'password' | password_hash('sha512') }}"
    register: results
    when: inventory_hostname in groups['local']
  - name: create user
    user:
      name: ansible
      password: "{{ hostvars[groups['local'][0]].pw_hash }}"
    when: inventory_hostname in groups['web']
  - name: sudo privileges 
    shell: 'echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible'
    when: inventory_hostname in groups['web']
  - name: copy control root public key to node
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    when: inventory_hostname in groups['web']
  - name: mount
    mount:
      path: /mnt
      src: /dev/sr0
      fstype: iso9660
      opts: ro,noauto
      state: mounted
    when: inventory_hostname in groups['web']
    tags: mount
  - name: setup repo
    shell: "{{ item }}"
    when: inventory_hostname in groups['web']
    loop:
      - 'dnf config-manager --add-repo=file:///mnt/AppStream'
      - 'dnf config-manager --add-repo=file:///mnt/BaseOS'
      - 'echo "gpgcheck=0" >> /etc/yum.repos.d/mnt_BaseOS.repo'
      - 'echo "gpgcheck=0" >> /etc/yum.repos.d/mnt_AppStream.repo'
  - name: install packages
    yum:
      name: "{{ item }}"
      state: latest
    when: inventory_hostname in groups['web']
    loop:
      - httpd
  - name: open http in firewalld
    firewalld:
      service: http
      state: enabled
      permanent: true
      immediate: true
    when: inventory_hostname in groups['web']
  - name: restart firewalld
    service:
      name: firewalld
      state: restarted
    when: inventory_hostname in groups['web']
  - name: start and enable httpd
    service:
      name: httpd
      state: restarted
      enabled: true
    when: inventory_hostname in groups['web']
  - name: toggle off ask_pass
    lineinfile:
      path: ./ansible.cfg
      regex: '^ask_pass'
      line: ask_pass=false
    when: inventory_hostname in groups['local']
  - name: change remote_user
    lineinfile:
      path: ./ansible.cfg
      regex: '^remote_user'
      line: remote_user=ansible
    when: inventory_hostname in groups['local']
