---

- name: initial-setup
  hosts: all
  become: true
  tasks:
  - name: create password hash
    set_fact: 
      pw_hash: "{{ 'password' | password_hash('sha512') }}"
    register: results
    when: inventory_hostname in groups['local']
  - name: create scc and Roles directory
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
      - ./Roles
      - ./scc
    when: inventory_hostname in groups['local']
  - name: download stig files
    unarchive:
      src: "{{ item }}"
      dest: ./scc
      remote_src: true
    when: inventory_hostname in groups['local']
    loop:
      - 'https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.10.1_rhel9_oracle-linux9_x86_64_bundle.zip'
      - 'https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_RHEL_9_V2R3_STIG_Ansible.zip'
  - name: unzip rhel9STIG-ansible.zip
    unarchive: 
      src: ./scc/rhel9STIG-ansible.zip
      dest: ./scc/
    when: inventory_hostname in groups['local']
  - name: copy ansible role to Roles
    copy:
      src: ./scc/roles/rhel9STIG
      dest: ./Roles/
    when: inventory_hostname in groups['local']
  - name: generate scan executable
    copy:
      dest: ./scan.sh
      mode: '0755'
      content: |
        #!/bin/bash
        ssh root@{{ hostvars['node2']['ansible_host'] }} sudo /opt/scc/cscc
    when: inventory_hostname in groups['local']
  - name: generate root SSH keypair with the default values and no passphrase for control
    community.crypto.openssh_keypair:
      path: /root/.ssh/id_rsa
      owner: root
      group: root
    when: inventory_hostname in groups['local']
  - name: create user
    user:
      name: ansible
      password: "{{ hostvars[groups['local'][0]].pw_hash }}"
    when: inventory_hostname in groups['rhel9']
  - name: sudo privileges 
    shell: 'echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible'
    when: inventory_hostname in groups['rhel9']
  - name: copy control root public key to node
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    when: inventory_hostname in groups['rhel9']
  - name: copy scc rpm to node
    copy: 
      src: ./scc/scc-5.10.1_rhel9_x86_64
      dest: /tmp
    when: inventory_hostname in groups['rhel9']
  - name: install scc
    shell: 'dnf install /tmp/scc-5.10.1_rhel9_x86_64/scc-5.10.1.rhel9.x86_64.rpm --nogpgcheck -y'
    when: inventory_hostname in groups['rhel9']
  - name: toggle off ask_pass
    lineinfile:
      path: ./ansible.cfg
      regex: '^ask_pass'
      line: ask_pass=false
    when: inventory_hostname in groups['local']
  - name: change remote_user
    lineinfile:
      path: ./ansible.cfg
      regex: '^remote_user'
      line: remote_user=ansible
    when: inventory_hostname in groups['local']
